title: Craig T. Russell, PhD
theme: minima
markdown: kramdown

# Minima settings
minima:
  skin: auto  # Automatically switches between light and dark mode
  
  # Social links
  social_links:
    - title: GitHub Profile
      icon: github
      url: "https://github.com/ctr26"
    - title: LinkedIn Profile
      icon: linkedin
      url: "https://linkedin.com/in/ctr26"
    - title: Google Scholar Profile
      icon: graduation-cap
      url: "https://scholar.google.com/citations?user=XVt7BYQAAAAJ&hl=en"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site metadata
  
description: >

